spring.application.name=backend



spring.datasource.url=jdbc:postgresql://db:5432/sportify_db
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

spring.mvc.cors.allowed-origins=http://localhost:5173,http://localhost:3000
spring.mvc.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
spring.mvc.cors.allowed-headers=*
spring.mvc.cors.allow-credentials=true

server.port=8080
server.servlet.context-path=/api

mercadopago.token-acceso=TEST-5727078962992321-051715-3f21c0f28279a01d8d461ee9424eefe4-154404288
mercadopago.clave-publica=TEST-f0bac376-a059-4a7b-8c41-ab748e316462

logging.level.root=INFO
logging.level.com.sportify=DEBUG